version: "3"
services:
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    volumes:
      - ./deploy:/acme.sh/deploy
      - ./issue-cert.sh:/issue-cert.sh:ro
    env_file: ./config.env
    command: [ "daemon" ]
    network_mode: host
    restart: unless-stopped
